version: '3'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - .data/db:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=lugdocker
      - MYSQL_PASSWORD=lugdocker
      - MYSQL_DATABASE=lugdocker
      - MYSQL_USER=lugdocker

  app:
    image: nextcloud
    ports:
      - 80
    links:
      - db
    volumes:
      - .data/nextcloud:/var/www/html
    restart: always
    environment:
      - VIRTUAL_HOST=lugdocker.eecs.wsu.edu
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=lugdocker.eecs.wsu.edu
      - LETSENCRYPT_EMAIL=$LUG_EMAIL

networks:
  default:
    external:
      name: webproxy
